trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Replace these with your Docker Hub or Azure Container Registry information
  dockerRegistryServiceConnection: 'DockerRegistry'
  imageName: ‘app.py’

steps:
- task: DockerInstaller@0
 
- script: |
    docker build -t $(imageName) .
    docker tag $(imageName) $(dockerRegistryServiceConnection)/$(imageName):$(Build.BuildId)
    docker push $(dockerRegistryServiceConnection)/$(imageName):$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- script: echo Build and push completed
  displayName: 'Build Completed'


